import type { CuratedOperator } from "@/lib/schemas/operator.schema";

export const OPERATOR_SEED: CuratedOperator[] = [
  {
    username: "mxstermind",
    name: "Mxstermind",
    role: "Founder / executive",
    yearsExp: 6,
    availability: "available-now",
    amanahScore: 98,
    completionRate: 97,
    bio: "The guarantor behind every deal on this platform. Builds high-trust operator teams for founders and brands.",
    bestResult: "Built and coordinated multi-role delivery teams that shipped products and growth systems in weeks.",
    wontTakeOn: "Vague briefs, no owner on the client side, and projects without clear accountability.",
    startingPrice: "EUR 497",
    pricingModel: "Fixed package",
    skills: ["n8n", "Next.js", "Growth systems"],
    idealClient: "Founders needing one accountable lead",
    workStyle: "Hands-on management with weekly checkpoints",
    typicalTimeline: "1-3 weeks",
    proofLink: "https://brandforge.gg/mxstermind",
    faq: [
      {
        question: "What do you actually do in the engagement?",
        answer: "I scope the work, select the right operator, and stay accountable through delivery.",
      },
      {
        question: "When should a client talk to you first?",
        answer: "When they need execution fast and one responsible point of contact.",
      },
      {
        question: "What makes you decline a project?",
        answer: "Unclear outcomes, unrealistic deadlines, or a client without a decision owner.",
      },
    ],
    isVerified: true,
    layoutSpan: "featured",
    displayOrder: 1,
  },
  {
    username: "dipps",
    name: "Dipps",
    role: "Software engineer",
    yearsExp: 7,
    availability: "available",
    amanahScore: 93,
    completionRate: 95,
    bio: "Engineer focused on robust product architecture and maintainable delivery.",
    bestResult: "Stabilized critical app architecture and reduced production regressions across releases.",
    wontTakeOn: "Patchwork projects with no technical owner and no quality standard.",
    startingPrice: "EUR 1,500",
    pricingModel: "Project-based",
    skills: ["Backend systems", "API design", "Reliability"],
    idealClient: "Teams rebuilding core systems",
    workStyle: "Milestone-driven with technical review gates",
    typicalTimeline: "2-4 weeks",
    proofLink: "https://brandforge.gg/dipps",
    faq: [],
    isVerified: true,
    layoutSpan: "compact",
    displayOrder: 2,
  },
  {
    username: "thami",
    name: "Thami",
    role: "Software engineer",
    yearsExp: 10,
    availability: "limited",
    amanahScore: 95,
    completionRate: 96,
    bio: "Senior engineer with a decade of shipping production systems.",
    bestResult: "Led multi-release delivery plans with consistent on-time milestones.",
    wontTakeOn: "Projects where decisions are repeatedly delayed and scope keeps shifting without ownership.",
    startingPrice: "EUR 2,000",
    pricingModel: "Sprint + advisory",
    skills: ["Platform engineering", "Architecture", "Delivery ops"],
    idealClient: "Scale-ups with complex architecture",
    workStyle: "Structured scope control and transparent tradeoffs",
    typicalTimeline: "3-6 weeks",
    proofLink: "https://brandforge.gg/thami",
    faq: [],
    isVerified: true,
    layoutSpan: "standard",
    displayOrder: 3,
  },
  {
    username: "nero",
    name: "Nero",
    role: "Developer / engineer",
    yearsExp: 12,
    availability: "limited",
    amanahScore: 96,
    completionRate: 97,
    bio: "Twelve years delivering software products across engineering and architecture tracks.",
    bestResult: "Turned fragmented codebases into scalable product systems ready for growth.",
    wontTakeOn: "No-scope rush projects that skip architecture and QA by design.",
    startingPrice: "EUR 2,500",
    pricingModel: "Retainer",
    skills: ["Full-stack delivery", "System design", "Scale readiness"],
    idealClient: "Teams preparing for growth-stage scale",
    workStyle: "Architecture-first with strict production discipline",
    typicalTimeline: "4-8 weeks",
    proofLink: "https://brandforge.gg/nero",
    faq: [],
    isVerified: true,
    layoutSpan: "standard",
    displayOrder: 4,
  },
  {
    username: "vectura",
    name: "Vectura",
    role: "Frontend + backend developer",
    yearsExp: 8,
    availability: "available",
    amanahScore: 92,
    completionRate: 94,
    bio: "Product-oriented full-stack builder across frontend and backend workflows.",
    bestResult: "Shipped integrated product features end-to-end without handoff bottlenecks.",
    wontTakeOn: "Design-only engagements with no product ownership and no release path.",
    startingPrice: "EUR 1,800",
    pricingModel: "Feature sprint",
    skills: ["Next.js", "Supabase", "Full-stack features"],
    idealClient: "Lean teams that need end-to-end feature shipping",
    workStyle: "Fast iteration with production-safe releases",
    typicalTimeline: "1-3 weeks",
    proofLink: "https://brandforge.gg/vectura",
    faq: [],
    isVerified: true,
    layoutSpan: "compact",
    displayOrder: 5,
  },
  {
    username: "nik",
    name: "Nik",
    role: "Web3 developer",
    yearsExp: 6,
    availability: "available",
    amanahScore: 91,
    completionRate: 93,
    bio: "Web3-focused engineer for practical blockchain product integrations.",
    bestResult: "Delivered secure wallet and transaction flows with production-ready UX and controls.",
    wontTakeOn: "Speculative token-first projects with no product utility or compliance awareness.",
    startingPrice: "EUR 1,900",
    pricingModel: "Project-based",
    skills: ["Web3 integration", "Smart contract workflows", "Wallet UX"],
    idealClient: "Products with real utility use-cases",
    workStyle: "Risk-first planning with secure rollout steps",
    typicalTimeline: "2-4 weeks",
    proofLink: "https://brandforge.gg/nik",
    faq: [],
    isVerified: true,
    layoutSpan: "compact",
    displayOrder: 6,
  },
  {
    username: "don-eros",
    name: "Don Eros",
    role: "Marketing specialist",
    yearsExp: 9,
    availability: "available",
    amanahScore: 94,
    completionRate: 95,
    bio: "Performance-minded marketer focused on messaging clarity and repeatable growth execution.",
    bestResult: "Improved campaign efficiency through cleaner positioning and tighter acquisition funnels.",
    wontTakeOn: "Vanity-first growth work without attribution, measurement, or outcome ownership.",
    startingPrice: "EUR 1,200",
    pricingModel: "Monthly retainer",
    skills: ["Campaign strategy", "Growth systems", "Offer positioning"],
    idealClient: "Teams needing measurable growth with ownership",
    workStyle: "Weekly experiment loops with clear attribution",
    typicalTimeline: "2-6 weeks",
    proofLink: "https://brandforge.gg/don-eros",
    faq: [],
    isVerified: true,
    layoutSpan: "standard",
    displayOrder: 7,
  },
  {
    username: "ae",
    name: "AE",
    role: "Graphic + motion designer",
    yearsExp: 7,
    availability: "limited",
    amanahScore: 93,
    completionRate: 94,
    bio: "Designer blending visual identity and motion to improve brand clarity and attention quality.",
    bestResult: "Built visual systems that improved campaign quality and consistency across channels.",
    wontTakeOn: "Unstructured creative requests with no brief, no references, and no decision owner.",
    startingPrice: "EUR 1,100",
    pricingModel: "Retainer + campaign packages",
    skills: ["Brand visuals", "Motion systems", "Social creative"],
    idealClient: "Brands needing consistent visual systems",
    workStyle: "Brief-first, system-driven creative production",
    typicalTimeline: "1-3 weeks",
    proofLink: "https://brandforge.gg/ae",
    faq: [],
    isVerified: true,
    layoutSpan: "standard",
    displayOrder: 8,
  },
];
