import type { Category, OfferBundle, Product, SellerProfile } from "./types";

export const CATEGORIES: Category[] = [
  { id: "ai", slug: "ai", name: "AI & Automation", description: "Agents, workflows, and revenue on autopilot", productCount: 412 },
  { id: "discord", slug: "discord", name: "Discord Growth Systems", description: "Servers, bots, and monetized communities", productCount: 287 },
  { id: "content", slug: "content", name: "Content Creation Systems", description: "Scripts, calendars, and repeatable output", productCount: 356 },
  { id: "video", slug: "video", name: "Short-form Video Systems", description: "TikTok, Reels, and Shorts pipelines", productCount: 298 },
  { id: "branding", slug: "branding", name: "Brand Identity", description: "Visuals and positioning that convert", productCount: 241 },
  { id: "landing", slug: "landing", name: "Landing Pages & Funnels", description: "Pages built to capture and close", productCount: 189 },
  { id: "leads", slug: "leads", name: "Lead Generation Systems", description: "Funnels that fill your DMs daily", productCount: 224 },
  { id: "business", slug: "business", name: "Digital Business Setup", description: "Store, stack, and launch without code", productCount: 167 },
  { id: "monetization", slug: "monetization", name: "Creator Monetization Systems", description: "Turn audience into recurring income", productCount: 203 },
  { id: "marketing", slug: "marketing", name: "Marketing Systems", description: "Ads, email, and growth loops", productCount: 276 },
];

export const SELLERS: SellerProfile[] = [
  {
    id: "forge-studio",
    name: "Forge Studio",
    role: "BrandForge official",
    bio: "High-velocity systems shipped by the forge team. Same-day scoping on Discord.",
    skills: ["AI", "Funnels", "Discord", "Short-form"],
    rating: 4.97,
    reviewCount: 1248,
    responseTime: "< 1h",
    completionRate: 99,
    productIds: [
      "ai-short-form-content-machine",
      "ai-automation-business-system",
      "discord-growth-monetization",
      "high-converting-landing-page",
      "lead-gen-funnel-system",
      "viral-content-strategy-pack",
    ],
    thumbGradient: "linear-gradient(135deg, #0a0505, #ff2a00, #ffc14d)",
  },
  {
    id: "nova-growth",
    name: "Nova Growth",
    role: "Creator & community systems",
    bio: "Built 40+ monetized Discords and faceless channels. Outcome-first delivery.",
    skills: ["Discord", "YouTube", "TikTok", "Monetization"],
    rating: 4.94,
    reviewCount: 512,
    responseTime: "< 2h",
    completionRate: 98,
    productIds: [
      "youtube-automation-system",
      "discord-engagement-bot-suite",
      "membership-community-setup",
      "tiktok-posting-system-setup",
    ],
    thumbGradient: "linear-gradient(135deg, #120818, #5865f2, #ff4d00)",
  },
  {
    id: "apex-funnels",
    name: "Apex Funnels",
    role: "Conversion & lead systems",
    bio: "Landing pages and DM funnels that pay for themselves in week one.",
    skills: ["Landing pages", "Lead gen", "Email", "Ads"],
    rating: 4.92,
    reviewCount: 318,
    responseTime: "< 3h",
    completionRate: 97,
    productIds: [
      "high-converting-landing-page",
      "lead-gen-funnel-system",
      "webinar-funnel-page",
      "cold-dm-outreach-system",
      "paid-ads-creative-pack",
    ],
    thumbGradient: "linear-gradient(135deg, #050508, #ff6b00, #ff2200)",
  },
  {
    id: "prism-brand",
    name: "Prism Brand Co.",
    role: "Identity & personal brand",
    bio: "Profiles and kits that make people DM you before you pitch.",
    skills: ["Branding", "Social kits", "Positioning", "Visuals"],
    rating: 5.0,
    reviewCount: 284,
    responseTime: "< 2h",
    completionRate: 100,
    productIds: ["personal-brand-growth-kit", "logo-social-kit-express", "ugc-ad-creator-kit"],
    thumbGradient: "linear-gradient(135deg, #1a0800, #ff6b00, #ffb800)",
  },
  {
    id: "stack-launch",
    name: "Stack Launch",
    role: "No-code business setup",
    bio: "Gumroad-style stores and business stacks live in days, not months.",
    skills: ["No-code", "Gumroad", "Notion", "Automations"],
    rating: 4.91,
    reviewCount: 176,
    responseTime: "< 4h",
    completionRate: 96,
    productIds: [
      "digital-product-store-setup",
      "llc-ready-business-starter",
      "gumroad-passive-income-ladder",
      "ai-chatbot-businesses",
    ],
    thumbGradient: "linear-gradient(135deg, #030305, #ff4d00, #881100)",
  },
];

const d = (items: string[]) => ({ includes: items, deliverables: items });

export const PRODUCTS: Product[] = [
  {
    id: "ai-short-form-content-machine",
    title: "AI Short-Form Content Machine",
    tagline: "Ideas → viral hooks → scripts → posting system in 48h",
    description:
      "Stop staring at a blank caption. We wire your niche into a repeatable Shorts/TikTok machine: hook formulas, AI script batching, and a weekly posting SOP your VA can run. Slots fill fast — message now if you want March momentum, not April regret.",
    ...d([
      "30 viral hook templates (your niche)",
      "AI script workflow (Notion + prompt pack)",
      "7-day content calendar pre-filled",
      "Posting checklist + repurposing map",
      "1 live Discord walkthrough",
    ]),
    useCases: [
      "Launch a faceless channel without hiring an editor",
      "Repurpose one long video into 12 Shorts per week",
      "Turn client calls into daily TikTok proof content",
    ],
    price: 249,
    priceLabel: "$249",
    categoryId: "ai",
    deliveryHours: 48,
    deliveryLabel: "24–48h",
    rating: 4.96,
    reviewCount: 842,
    sellerId: "forge-studio",
    featured: true,
    popular: true,
    popularityScore: 98,
    tags: ["TikTok", "Shorts", "AI scripts", "Hooks"],
    ctaText: "Contact on Discord",
    thumbGradient: "linear-gradient(135deg, #0a0505 0%, #ff4d00 50%, #ffb800 100%)",
  },
  {
    id: "ai-automation-business-system",
    title: "AI Automation Business System",
    tagline: "Lead capture + AI replies + workflows that book calls while you sleep",
    description:
      "Your DMs shouldn't be your bottleneck. We connect forms, sheets, CRM-lite, and AI auto-replies so every lead gets nurtured in minutes — not when you remember. Built for service sellers and agency owners who are losing deals to slow follow-up.",
    ...d([
      "Lead capture map (site, IG, Discord)",
      "AI reply templates (on-brand, safe)",
      "Make/n8n workflow (3 automations live)",
      "Notification + handoff to human",
      "Testing + 7-day tweak window",
    ]),
    useCases: [
      "Agency owner drowning in inbound DMs",
      "Coach selling high-ticket via discovery calls",
      "Discord community routing paid inquiries",
    ],
    price: 499,
    priceLabel: "$499",
    categoryId: "ai",
    deliveryHours: 72,
    deliveryLabel: "2–3 days",
    rating: 4.94,
    reviewCount: 391,
    sellerId: "forge-studio",
    featured: true,
    popular: true,
    popularityScore: 96,
    tags: ["Automation", "AI replies", "CRM", "Leads"],
    ctaText: "Contact on Discord",
    thumbGradient: "linear-gradient(135deg, #050510, #4a00ff33, #ff4d00)",
  },
  {
    id: "ai-chatbot-businesses",
    title: "AI Chatbot for Businesses",
    tagline: "Telegram, Discord, or site assistant that answers and qualifies 24/7",
    description:
      "Hiring support before revenue is backwards. Deploy a trained assistant that handles FAQs, pricing questions, and booking handoffs — you jump in only when money is on the line. Limited setup slots each week.",
    ...d([
      "Knowledge base ingest (docs/FAQ)",
      "Bot deployed (Telegram or Discord)",
      "Qualification flow (3 questions)",
      "Escalation to you + analytics sheet",
      "14-day prompt tuning",
    ]),
    useCases: [
      "SaaS pre-sales on website",
      "Course creator FAQ in Telegram",
      "Local business after-hours inquiries",
    ],
    price: 349,
    priceLabel: "$349",
    categoryId: "ai",
    deliveryHours: 96,
    deliveryLabel: "3–4 days",
    rating: 4.91,
    reviewCount: 267,
    sellerId: "stack-launch",
    featured: true,
    popular: true,
    popularityScore: 91,
    tags: ["Chatbot", "Telegram", "Discord", "Support"],
    ctaText: "Contact on Discord",
    thumbGradient: "linear-gradient(135deg, #030305, #ff2200, #ffb800)",
  },
  {
    id: "ai-voice-agent-inbox",
    title: "AI Voice + Inbox Agent",
    tagline: "Voice notes transcribed, summarized, and drafted into replies",
    description:
      "Creators living in voice notes finally get a system: transcribe, tag, draft replies, and queue follow-ups. Stop losing deals in unread threads.",
    ...d(["Voice → text pipeline", "Reply draft prompts", "Inbox tags + SOP", "Discord setup call"]),
    useCases: ["Busy founder on WhatsApp/Telegram", "Sales rep handling 50+ threads", "Creator management inbox"],
    price: 199,
    priceLabel: "$199",
    categoryId: "ai",
    deliveryHours: 48,
    deliveryLabel: "48h",
    rating: 4.88,
    reviewCount: 118,
    sellerId: "stack-launch",
    featured: false,
    popular: false,
    popularityScore: 78,
    tags: ["Voice", "Inbox", "AI"],
    ctaText: "Contact on Discord",
    thumbGradient: "linear-gradient(135deg, #0c0810, #ff4d00, #ff8c00)",
  },
  {
    id: "discord-growth-monetization",
    title: "Discord Growth + Monetization Setup",
    tagline: "Server architecture + bots + engagement loops + paid tier structure",
    description:
      "A dead server is a dead business. We build the channel flow, onboarding, bots, and monetization ladder so members know exactly how to engage and upgrade. Most teams waste months guessing — you get the playbook in days.",
    ...d([
      "Server blueprint (channels + roles)",
      "Welcome + rules + onboarding bot",
      "Engagement loops (events, streaks, XP)",
      "Monetization map (free → paid tiers)",
      "Launch checklist + 30-day growth plan",
    ]),
    useCases: [
      "Crypto/NFT community relaunch",
      "Course cohort community",
      "Paid mastermind with tiered access",
    ],
    price: 399,
    priceLabel: "$399",
    categoryId: "discord",
    deliveryHours: 72,
    deliveryLabel: "2–3 days",
    rating: 4.95,
    reviewCount: 623,
    sellerId: "forge-studio",
    featured: true,
    popular: true,
    popularityScore: 97,
    tags: ["Discord", "Monetization", "Bots", "Community"],
    ctaText: "Contact on Discord",
    thumbGradient: "linear-gradient(135deg, #120818 0%, #5865f2 30%, #ff4d00 100%)",
  },
  {
    id: "discord-engagement-bot-suite",
    title: "Discord Engagement Bot Suite",
    tagline: "XP, streaks, giveaways, and mod tools — live in 24h",
    description:
      "Retention beats acquisition. Ship bots that reward daily show-up so your server feels alive without you babysitting chat.",
    ...d(["XP + level system", "Streak tracker", "Giveaway module", "Mod commands", "Deploy guide"]),
    useCases: ["Gaming community", "Trading signals group", "Creator fan server"],
    price: 179,
    priceLabel: "$179",
    categoryId: "discord",
    deliveryHours: 24,
    deliveryLabel: "24h",
    rating: 4.89,
    reviewCount: 334,
    sellerId: "nova-growth",
    featured: false,
    popular: true,
    popularityScore: 86,
    tags: ["Bot", "Engagement", "Retention"],
    ctaText: "Contact on Discord",
    thumbGradient: "linear-gradient(135deg, #5865f2, #ff4d00, #030305)",
  },
  {
    id: "discord-paid-access-ladder",
    title: "Discord Paid Access Ladder",
    tagline: "Stripe-ready tier map + role automation + upgrade flows",
    description:
      "Turn free members into paying members with a clear ladder — VIP, pro, inner circle — wired to roles automatically.",
    ...d(["3-tier offer map", "Role automation spec", "Upgrade DM scripts", "Webhook integration guide"]),
    useCases: ["Paid alpha group", "Coaching community", "Exclusive content club"],
    price: 149,
    priceLabel: "$149",
    categoryId: "discord",
    deliveryHours: 36,
    deliveryLabel: "24–36h",
    rating: 4.87,
    reviewCount: 201,
    sellerId: "nova-growth",
    featured: false,
    popular: false,
    popularityScore: 82,
    tags: ["Paid community", "Tiers", "Stripe"],
    ctaText: "Contact on Discord",
    thumbGradient: "linear-gradient(135deg, #1a0a00, #5865f2, #ffb800)",
  },
  {
    id: "viral-content-strategy-pack",
    title: "Viral Content Strategy Pack",
    tagline: "30-day growth plan + scripts + ideas — start posting tomorrow",
    description:
      "You don't need more tools — you need a plan that ships. Thirty days of angles, scripts, and CTAs matched to your offer, plus a Notion command center. Perfect if you've been 'about to post' for three weeks.",
    ...d([
      "30-day content calendar",
      "60 script outlines (short + long)",
      "Hook swipe file (100 lines)",
      "CTA variants per platform",
      "Weekly review template",
    ]),
    useCases: ["New personal brand", "Agency founder building authority", "Product launch warmup"],
    price: 129,
    priceLabel: "$129",
    categoryId: "content",
    deliveryHours: 24,
    deliveryLabel: "12–24h",
    rating: 4.97,
    reviewCount: 1104,
    sellerId: "forge-studio",
    featured: true,
    popular: true,
    popularityScore: 95,
    tags: ["Strategy", "Scripts", "Calendar", "Growth"],
    ctaText: "Contact on Discord",
    thumbGradient: "linear-gradient(135deg, #0a0505 0%, #ff2a00 40%, #ffc14d 100%)",
  },
  {
    id: "content-repurpose-engine",
    title: "Content Repurpose Engine",
    tagline: "One long video → 20 clips + captions + queue",
    description:
      "Stop posting once and praying. Systematize clipping, captions, and scheduling so one recording fuels the whole week.",
    ...d(["Repurpose SOP", "Caption style guide", "Clip naming system", "Scheduling workflow"]),
    useCases: ["Podcast host", "YouTube educator", "Agency repurposing client wins"],
    price: 159,
    priceLabel: "$159",
    categoryId: "content",
    deliveryHours: 36,
    deliveryLabel: "24–36h",
    rating: 4.9,
    reviewCount: 445,
    sellerId: "forge-studio",
    featured: false,
    popular: true,
    popularityScore: 88,
    tags: ["Repurpose", "Clips", "Workflow"],
    ctaText: "Contact on Discord",
    thumbGradient: "linear-gradient(135deg, #0c0810, #ff4d00, #ff8c00)",
  },
  {
    id: "youtube-automation-system",
    title: "YouTube Automation System",
    tagline: "Faceless channel setup + content pipeline + upload SOP",
    description:
      "Faceless is still the fastest path to ad revenue and offer traffic — if the pipeline isn't chaos. We deliver niche research, video structure, thumbnail rules, and a production calendar your editor (or AI) can run.",
    ...d([
      "Niche + positioning brief",
      "Video template (hook-body-CTA)",
      "Thumbnail rules + examples",
      "30-video topic bank",
      "Upload + SEO checklist",
    ]),
    useCases: ["New faceless channel", "Cash cow channel portfolio", "Agency productized YouTube service"],
    price: 449,
    priceLabel: "$449",
    categoryId: "video",
    deliveryHours: 96,
    deliveryLabel: "3–4 days",
    rating: 4.93,
    reviewCount: 528,
    sellerId: "nova-growth",
    featured: true,
    popular: true,
    popularityScore: 94,
    tags: ["YouTube", "Faceless", "Automation", "Pipeline"],
    ctaText: "Contact on Discord",
    thumbGradient: "linear-gradient(135deg, #ff0000 0%, #ff4d00 45%, #1a0500 100%)",
  },
  {
    id: "tiktok-posting-system-setup",
    title: "TikTok Posting System Setup",
    tagline: "Batch film → schedule → analyze — no more random posting",
    description:
      "Viral is a volume game with rules. Get the batching rhythm, analytics sheet, and hook rotation that top creators use daily.",
    ...d(["Batch filming SOP", "Scheduler setup", "Analytics tracker", "Hook rotation sheet"]),
    useCases: ["Ecom brand daily posts", "Coach authority play", "Affiliate account farm"],
    price: 99,
    priceLabel: "$99",
    categoryId: "video",
    deliveryHours: 24,
    deliveryLabel: "24h",
    rating: 4.9,
    reviewCount: 712,
    sellerId: "nova-growth",
    featured: false,
    popular: true,
    popularityScore: 90,
    tags: ["TikTok", "Scheduling", "Batching"],
    ctaText: "Contact on Discord",
    thumbGradient: "linear-gradient(135deg, #0a0a12, #00f2ea33, #ff4d00)",
  },
  {
    id: "ugc-ad-creator-kit",
    title: "UGC Ad Creator Kit",
    tagline: "Scripts + shot list + hooks for paid social that doesn't flop",
    description:
      "Media buyers are desperate for creative that converts. Ship 15 UGC-style ad scripts with shot lists you can film on a phone today.",
    ...d(["15 ad scripts", "Shot list per script", "Hook variants", "Brief for creators"]),
    useCases: ["DTC brand testing creatives", "Agency creative pack", "Info product retargeting"],
    price: 189,
    priceLabel: "$189",
    categoryId: "video",
    deliveryHours: 48,
    deliveryLabel: "48h",
    rating: 4.86,
    reviewCount: 198,
    sellerId: "prism-brand",
    featured: false,
    popular: false,
    popularityScore: 84,
    tags: ["UGC", "Ads", "Scripts"],
    ctaText: "Contact on Discord",
    thumbGradient: "linear-gradient(135deg, #1a0800, #ff6b00, #ffb800)",
  },
  {
    id: "personal-brand-growth-kit",
    title: "Personal Brand Growth Kit",
    tagline: "Profile optimization + content strategy + visuals that get DMs",
    description:
      "People buy the person before the product. We rebuild your bio, banner, content pillars, and 14-day post plan so you look like the obvious choice in your niche — not another generic account.",
    ...d([
      "Profile audit + rewrite (IG/LinkedIn/X)",
      "Banner + avatar direction",
      "3 content pillars + post mix",
      "14-day post plan",
      "DM opener scripts",
    ]),
    useCases: ["Consultant going full-time online", "Founder building in public", "Creator relaunching after rebrand"],
    price: 299,
    priceLabel: "$299",
    categoryId: "branding",
    deliveryHours: 72,
    deliveryLabel: "2–3 days",
    rating: 4.98,
    reviewCount: 467,
    sellerId: "prism-brand",
    featured: true,
    popular: true,
    popularityScore: 93,
    tags: ["Personal brand", "Profile", "Strategy"],
    ctaText: "Contact on Discord",
    thumbGradient: "linear-gradient(135deg, #1a0800, #ff6b00, #ffb800)",
  },
  {
    id: "logo-social-kit-express",
    title: "Logo + Social Kit Express",
    tagline: "Logo, colors, type, and 9 social templates — 48h turnaround",
    description:
      "Stop launching with a Canva default. Get a tight identity and templates you can hand to any VA.",
    ...d(["Primary logo", "Color + type system", "9 social templates", "Export pack"]),
    useCases: ["Startup pre-launch", "Discord server rebrand", "New digital product line"],
    price: 149,
    priceLabel: "$149",
    categoryId: "branding",
    deliveryHours: 48,
    deliveryLabel: "24–48h",
    rating: 4.95,
    reviewCount: 356,
    sellerId: "prism-brand",
    featured: false,
    popular: true,
    popularityScore: 87,
    tags: ["Logo", "Templates", "Identity"],
    ctaText: "Contact on Discord",
    thumbGradient: "linear-gradient(135deg, #120800 0%, #ff8c00 45%, #ff4d00 100%)",
  },
  {
    id: "high-converting-landing-page",
    title: "High-Converting Landing Page Build",
    tagline: "Stripe-level design, conversion copy, deploy-ready — no checkout yet",
    description:
      "Traffic without a page that converts is burning money. We ship a mobile-first landing with proof, offer stack, and dual CTAs to Discord/Telegram — you close in DMs where trust is built.",
    ...d([
      "Wireframe + copy doc",
      "Designed page (Next.js or Framer)",
      "Deploy to Vercel/Cloudflare",
      "2 revision rounds",
      "Analytics + event hooks",
    ]),
    useCases: ["High-ticket service offer", "Waitlist for digital product", "Webinar registration"],
    price: 699,
    priceLabel: "$699",
    categoryId: "landing",
    deliveryHours: 120,
    deliveryLabel: "3–5 days",
    rating: 4.92,
    reviewCount: 289,
    sellerId: "apex-funnels",
    featured: true,
    popular: true,
    popularityScore: 92,
    tags: ["Landing page", "Conversion", "Web"],
    ctaText: "Contact on Discord",
    thumbGradient: "linear-gradient(135deg, #050508 0%, #ff6b00 55%, #ff2200 100%)",
  },
  {
    id: "webinar-funnel-page",
    title: "Webinar Funnel Page",
    tagline: "Registration → reminder flow → replay CTA — built to fill seats",
    description:
      "Webinars die on weak pages. Get the registration experience and email reminders mapped — you drive traffic, we handle the conversion structure.",
    ...d(["Registration page", "Thank-you + calendar", "Reminder email copy", "Replay page wire"]),
    useCases: ["Coach live training", "B2B demo webinar", "Product waitlist event"],
    price: 449,
    priceLabel: "$449",
    categoryId: "landing",
    deliveryHours: 96,
    deliveryLabel: "3–4 days",
    rating: 4.88,
    reviewCount: 142,
    sellerId: "apex-funnels",
    featured: false,
    popular: false,
    popularityScore: 79,
    tags: ["Webinar", "Funnel", "Registration"],
    ctaText: "Contact on Discord",
    thumbGradient: "linear-gradient(135deg, #030305, #ff2200, #ffb800)",
  },
  {
    id: "lead-gen-funnel-system",
    title: "Lead Generation Funnel System",
    tagline: "Landing page + automation + DM funnel — leads hit your inbox daily",
    description:
      "Ads and content mean nothing if leads evaporate. Full stack: capture page, auto-nurture, and DM scripts that book calls. This is the #1 request from agency owners in 2026.",
    ...d([
      "Lead magnet + landing wire",
      "Capture automation",
      "5-email/DM nurture sequence",
      "Booking handoff flow",
      "KPI tracker sheet",
    ]),
    useCases: ["Local service business", "B2B SaaS trials", "High-ticket coaching pipeline"],
    price: 599,
    priceLabel: "$599",
    categoryId: "leads",
    deliveryHours: 120,
    deliveryLabel: "4–5 days",
    rating: 4.94,
    reviewCount: 378,
    sellerId: "forge-studio",
    featured: true,
    popular: true,
    popularityScore: 95,
    tags: ["Lead gen", "Funnel", "DM", "Automation"],
    ctaText: "Contact on Discord",
    thumbGradient: "linear-gradient(135deg, #0a0018, #ff4d00, #ffb800)",
  },
  {
    id: "cold-dm-outreach-system",
    title: "Cold DM Outreach System",
    tagline: "Lists + scripts + follow-ups that don't get you flagged",
    description:
      "Outbound isn't dead — boring outreach is. Get compliant scripts, personalization tokens, and a daily quota system that lands clients without spam vibes.",
    ...d(["ICP list template", "20 DM scripts", "Follow-up cadence", "Tracking sheet"]),
    useCases: ["Agency client acquisition", "OnlyFans management outreach", "B2B founder sales"],
    price: 129,
    priceLabel: "$129",
    categoryId: "leads",
    deliveryHours: 24,
    deliveryLabel: "24h",
    rating: 4.85,
    reviewCount: 512,
    sellerId: "apex-funnels",
    featured: false,
    popular: true,
    popularityScore: 89,
    tags: ["Outreach", "DM", "Sales"],
    ctaText: "Contact on Discord",
    thumbGradient: "linear-gradient(135deg, #050508, #ff6b00, #030305)",
  },
  {
    id: "digital-product-store-setup",
    title: "Digital Product Store Setup (No-code)",
    tagline: "Gumroad/Notion-style store live — products, delivery, and branding",
    description:
      "You already have knowledge worth selling. We build the store, product pages, delivery emails, and upsell path so you can launch this weekend — not after another 'platform research' rabbit hole.",
    ...d([
      "Store platform setup (Gumroad/Lemon/Lemon-style)",
      "3 product listings written",
      "Delivery email templates",
      "Upsell + bundle map",
      "Launch checklist",
    ]),
    useCases: ["Template seller", "Course creator first offer", "Notion dashboard shop"],
    price: 349,
    priceLabel: "$349",
    categoryId: "business",
    deliveryHours: 72,
    deliveryLabel: "2–3 days",
    rating: 4.93,
    reviewCount: 441,
    sellerId: "stack-launch",
    featured: true,
    popular: true,
    popularityScore: 91,
    tags: ["Gumroad", "No-code", "Digital products"],
    ctaText: "Contact on Discord",
    thumbGradient: "linear-gradient(135deg, #111, #333, #ff4d00)",
  },
  {
    id: "llc-ready-business-starter",
    title: "LLC-Ready Business Starter",
    tagline: "Brand name, offer stack, legal checklist, and launch page outline",
    description:
      "Stop mixing personal and business accounts. Get the entity checklist, offer positioning, and asset list founders use before first sale.",
    ...d(["Name + positioning workshop", "Offer stack doc", "LLC checklist (US)", "Launch asset list"]),
    useCases: ["First-time founder", "Side hustle going full-time", "Agency productization"],
    price: 199,
    priceLabel: "$199",
    categoryId: "business",
    deliveryHours: 48,
    deliveryLabel: "48h",
    rating: 4.87,
    reviewCount: 156,
    sellerId: "stack-launch",
    featured: false,
    popular: false,
    popularityScore: 76,
    tags: ["LLC", "Startup", "Offer"],
    ctaText: "Contact on Discord",
    thumbGradient: "linear-gradient(135deg, #030305, #ff4d00, #881100)",
  },
  {
    id: "gumroad-passive-income-ladder",
    title: "Gumroad Passive Income Ladder",
    tagline: "Tripwire → core offer → premium — priced and wired",
    description:
      "One product is a hobby. A ladder is a business. We map your three offers, pricing psychology, and email/DM upsell path.",
    ...d(["3-tier offer map", "Pricing sheet", "Upsell email/DM copy", "Launch sequence"]),
    useCases: ["Notion template shop", "Design asset packs", "Mini-course seller"],
    price: 179,
    priceLabel: "$179",
    categoryId: "monetization",
    deliveryHours: 36,
    deliveryLabel: "24–36h",
    rating: 4.9,
    reviewCount: 298,
    sellerId: "stack-launch",
    featured: false,
    popular: true,
    popularityScore: 85,
    tags: ["Gumroad", "Pricing", "Upsell"],
    ctaText: "Contact on Discord",
    thumbGradient: "linear-gradient(135deg, #0a0505, #ffb800, #ff4d00)",
  },
  {
    id: "membership-community-setup",
    title: "Membership Community Setup",
    tagline: "Recurring offer + onboarding + retention playbook",
    description:
      "Subscriptions beat one-off if retention is designed. We build the offer, onboarding, and monthly value calendar for Discord or Skool-style communities.",
    ...d(["Membership offer doc", "Onboarding flow", "Monthly value calendar", "Churn save scripts"]),
    useCases: ["Trading community", "Fitness coaching group", "Creator fan club"],
    price: 399,
    priceLabel: "$399",
    categoryId: "monetization",
    deliveryHours: 72,
    deliveryLabel: "2–3 days",
    rating: 4.91,
    reviewCount: 187,
    sellerId: "nova-growth",
    featured: false,
    popular: false,
    popularityScore: 83,
    tags: ["Membership", "Recurring", "Community"],
    ctaText: "Contact on Discord",
    thumbGradient: "linear-gradient(135deg, #120818, #ff4d00, #ffb800)",
  },
  {
    id: "paid-ads-creative-pack",
    title: "Paid Ads Creative Pack",
    tagline: "20 static + 10 video ad concepts with hooks that stop the scroll",
    description:
      "CPMs rose. Creative is the lever. Get ad concepts aligned to your offer with hooks written for Meta/TikTok — film this week, test next week.",
    ...d(["20 static concepts", "10 video ad outlines", "Hook library", "Testing matrix"]),
    useCases: ["Ecom brand scaling", "Info product retargeting", "Agency client deliverable"],
    price: 249,
    priceLabel: "$249",
    categoryId: "marketing",
    deliveryHours: 48,
    deliveryLabel: "48h",
    rating: 4.89,
    reviewCount: 224,
    sellerId: "apex-funnels",
    featured: false,
    popular: true,
    popularityScore: 88,
    tags: ["Ads", "Meta", "TikTok", "Creative"],
    ctaText: "Contact on Discord",
    thumbGradient: "linear-gradient(135deg, #050508, #ff6b00, #ff2200)",
  },
  {
    id: "email-nurture-sequence-system",
    title: "Email Nurture Sequence System",
    tagline: "7-email sequence that warms cold leads before the DM close",
    description:
      "Email isn't dead — boring email is. Seven emails that teach, proof, and push to Discord/Telegram booking.",
    ...d(["7 emails written", "Subject line variants", "Segmentation map", "CTA to DM flow"]),
    useCases: ["Newsletter → client pipeline", "Lead magnet follow-up", "Webinar no-show recovery"],
    price: 149,
    priceLabel: "$149",
    categoryId: "marketing",
    deliveryHours: 36,
    deliveryLabel: "24–36h",
    rating: 4.86,
    reviewCount: 167,
    sellerId: "apex-funnels",
    featured: false,
    popular: false,
    popularityScore: 80,
    tags: ["Email", "Nurture", "Sequence"],
    ctaText: "Contact on Discord",
    thumbGradient: "linear-gradient(135deg, #0a0018, #ff4d00, #030305)",
  },
];

export const OFFERS: OfferBundle[] = [
  {
    id: "creator-launch-drop",
    title: "Creator Launch Drop",
    tagline: "Viral plan + personal brand + Shorts machine — ship content in 72h",
    price: 499,
    priceLabel: "$499",
    originalPrice: 677,
    deliveryLabel: "72h bundle",
    limited: true,
    badge: "DROP",
    includes: ["Viral Content Strategy Pack", "Personal Brand Growth Kit", "AI Short-Form Content Machine"],
    productIds: ["viral-content-strategy-pack", "personal-brand-growth-kit", "ai-short-form-content-machine"],
    thumbGradient: "linear-gradient(135deg, #ff2200, #ffb800, #1a0500)",
  },
  {
    id: "discord-money-machine",
    title: "Discord Money Machine",
    tagline: "Growth server + engagement bots + paid ladder",
    price: 599,
    priceLabel: "$599",
    originalPrice: 727,
    deliveryLabel: "4-day bundle",
    limited: true,
    badge: "HOT",
    includes: ["Discord Growth + Monetization", "Engagement Bot Suite", "Paid Access Ladder"],
    productIds: ["discord-growth-monetization", "discord-engagement-bot-suite", "discord-paid-access-ladder"],
    thumbGradient: "linear-gradient(135deg, #5865f2, #ff4d00, #030305)",
  },
  {
    id: "full-funnel-stack",
    title: "Full Funnel Stack",
    tagline: "Landing + lead gen + AI automation — close in DMs",
    price: 999,
    priceLabel: "$999",
    originalPrice: 1597,
    deliveryLabel: "7-day bundle",
    badge: "MAX",
    includes: ["High-Converting Landing Page", "Lead Gen Funnel System", "AI Automation Business System"],
    productIds: ["high-converting-landing-page", "lead-gen-funnel-system", "ai-automation-business-system"],
    thumbGradient: "linear-gradient(135deg, #0a0018, #ff4d00, #ffb800)",
  },
  {
    id: "faceless-youtube-empire",
    title: "Faceless YouTube Empire",
    tagline: "YouTube pipeline + repurpose engine + TikTok system",
    price: 649,
    priceLabel: "$649",
    originalPrice: 907,
    deliveryLabel: "5-day bundle",
    badge: "VALUE",
    includes: ["YouTube Automation System", "Content Repurpose Engine", "TikTok Posting System"],
    productIds: ["youtube-automation-system", "content-repurpose-engine", "tiktok-posting-system-setup"],
    thumbGradient: "linear-gradient(135deg, #ff0000, #ff4d00, #1a0500)",
  },
  {
    id: "digital-business-box",
    title: "Digital Business in a Box",
    tagline: "Store setup + landing page + chatbot — launch without code",
    price: 899,
    priceLabel: "$899",
    originalPrice: 1397,
    deliveryLabel: "6-day bundle",
    includes: ["Digital Product Store Setup", "High-Converting Landing Page", "AI Chatbot for Businesses"],
    productIds: ["digital-product-store-setup", "high-converting-landing-page", "ai-chatbot-businesses"],
    thumbGradient: "linear-gradient(135deg, #111, #ff4d00, #ffb800)",
  },
  {
    id: "growth-marketing-surge",
    title: "Growth Marketing Surge",
    tagline: "Viral strategy + ads pack + email nurture",
    price: 399,
    priceLabel: "$399",
    originalPrice: 527,
    deliveryLabel: "3-day bundle",
    badge: "NEW",
    includes: ["Viral Content Strategy Pack", "Paid Ads Creative Pack", "Email Nurture Sequence"],
    productIds: ["viral-content-strategy-pack", "paid-ads-creative-pack", "email-nurture-sequence-system"],
    thumbGradient: "linear-gradient(135deg, #050508, #ff6b00, #ffc14d)",
  },
];
