import type { Category, OfferBundle, Product, SellerProfile } from "./types";

export const CATEGORIES: Category[] = [
  { id: "ai", slug: "ai", name: "AI Systems", description: "Bots, agents, automation", productCount: 132 },
  { id: "discord", slug: "discord", name: "Discord Growth", description: "Servers, bots, community", productCount: 89 },
  { id: "branding", slug: "branding", name: "Branding", description: "Identity, kits, visuals", productCount: 214 },
  { id: "landing", slug: "landing", name: "Landing Pages", description: "High-converting pages", productCount: 76 },
  { id: "automation", slug: "automation", name: "Automation", description: "Workflows & integrations", productCount: 97 },
  { id: "content", slug: "content", name: "Content Systems", description: "Social, video, copy", productCount: 118 },
  { id: "templates", slug: "templates", name: "Templates", description: "Ready-to-ship assets", productCount: 188 },
];

export const SELLERS: SellerProfile[] = [
  {
    id: "prince",
    name: "Prince",
    role: "Graphic & motion designer",
    bio: "Eight years crafting visual brands. 182 consecutive 5-star vouches.",
    skills: ["Logos", "Banners", "Motion", "Brand kits"],
    rating: 5.0,
    reviewCount: 182,
    responseTime: "< 2h",
    completionRate: 100,
    productIds: ["brand-kit-pro", "discord-nitro-branding"],
    thumbGradient: "linear-gradient(135deg, #1a0a00, #ff4d00, #ffb800)",
  },
  {
    id: "dipps",
    name: "Dipako Thupayatlase",
    role: "Full-stack engineer",
    bio: "Web apps, automation, AI voice systems — sprint-based delivery.",
    skills: ["Java", "React", "Node", "Automation"],
    rating: 4.9,
    reviewCount: 64,
    responseTime: "< 4h",
    completionRate: 98,
    productIds: ["ai-discord-bot", "automation-workflow"],
    thumbGradient: "linear-gradient(135deg, #050508, #ff6b00, #ff2200)",
  },
  {
    id: "forge-studio",
    name: "Forge Studio",
    role: "BrandForge official",
    bio: "Curated high-velocity packs shipped by the forge team.",
    skills: ["Landing pages", "Growth", "Discord", "AI"],
    rating: 4.95,
    reviewCount: 512,
    responseTime: "< 1h",
    completionRate: 99,
    productIds: ["landing-page-build", "creator-growth-pack", "ai-automation-starter"],
    thumbGradient: "linear-gradient(135deg, #0a0505, #ff2a00, #ffc14d)",
  },
];

export const PRODUCTS: Product[] = [
  {
    id: "ai-automation-starter",
    title: "AI Automation Starter",
    tagline: "Workflow + bot hookup for your stack",
    description: "Scoped automation: triggers, webhooks, and one AI worker wired to your tools.",
    includes: ["Discovery call", "Workflow map", "1 automation lane live", "7-day tweak window"],
    price: 99,
    priceLabel: "$99",
    categoryId: "ai",
    deliveryHours: 24,
    deliveryLabel: "24h",
    rating: 4.9,
    reviewCount: 214,
    sellerId: "forge-studio",
    featured: true,
    popular: true,
    tags: ["AI", "Automation"],
    thumbGradient: "linear-gradient(135deg, #0a0505 0%, #ff4d00 50%, #ffb800 100%)",
  },
  {
    id: "ai-discord-bot",
    title: "AI Discord Bot",
    tagline: "Custom bot with moderation + AI replies",
    description: "Production Discord bot: slash commands, mod tools, optional GPT replies.",
    includes: ["Bot source", "Deploy guide", "3 command modules", "14-day support"],
    price: 149,
    priceLabel: "$149",
    categoryId: "ai",
    deliveryHours: 48,
    deliveryLabel: "24–48h",
    rating: 4.9,
    reviewCount: 128,
    sellerId: "dipps",
    featured: true,
    popular: true,
    tags: ["Discord", "AI", "Bot"],
    thumbGradient: "linear-gradient(135deg, #1a0a00 0%, #ff4d00 50%, #ff8c00 100%)",
  },
  {
    id: "discord-setup-pro",
    title: "Discord Server Setup",
    tagline: "Full server architecture + roles",
    description: "Channels, roles, permissions, welcome flow, and bot placeholders.",
    includes: ["Server blueprint", "Role kit", "Welcome + rules", "Emoji pack slot"],
    price: 149,
    priceLabel: "$149",
    categoryId: "discord",
    deliveryHours: 36,
    deliveryLabel: "24–36h",
    rating: 4.8,
    reviewCount: 203,
    sellerId: "forge-studio",
    featured: true,
    popular: false,
    tags: ["Discord", "Community"],
    thumbGradient: "linear-gradient(135deg, #120818 0%, #5865f2 30%, #ff4d00 100%)",
  },
  {
    id: "discord-nitro-branding",
    title: "Discord Nitro Branding Pack",
    tagline: "Banner, icon, invite splash",
    description: "Nitro-ready assets for server and profile branding.",
    includes: ["Server banner", "Icon set", "Invite background", "Source files"],
    price: 49,
    priceLabel: "$49",
    categoryId: "discord",
    deliveryHours: 12,
    deliveryLabel: "6–12h",
    rating: 4.9,
    reviewCount: 412,
    sellerId: "prince",
    featured: false,
    popular: true,
    tags: ["Branding", "Discord"],
    thumbGradient: "linear-gradient(135deg, #120800 0%, #ff8c00 45%, #ff4d00 100%)",
  },
  {
    id: "brand-kit-pro",
    title: "Brand Kit Pro",
    tagline: "Logo, colors, type, social kit",
    description: "Complete visual identity for creators and startups.",
    includes: ["Primary logo", "Color system", "Type pairing", "Social templates"],
    price: 79,
    priceLabel: "$79",
    categoryId: "branding",
    deliveryHours: 48,
    deliveryLabel: "24–48h",
    rating: 5.0,
    reviewCount: 156,
    sellerId: "prince",
    featured: true,
    popular: true,
    tags: ["Branding", "Logo"],
    thumbGradient: "linear-gradient(135deg, #1a0800, #ff6b00, #ffb800)",
  },
  {
    id: "landing-page-build",
    title: "Landing Page Build",
    tagline: "Conversion-focused single page",
    description: "Mobile-first landing with hero, proof, CTA — ready to deploy.",
    includes: ["Wireframe", "Designed page", "Deploy on Vercel/CF", "2 revision rounds"],
    price: 399,
    priceLabel: "$399",
    categoryId: "landing",
    deliveryHours: 120,
    deliveryLabel: "3–5 days",
    rating: 4.8,
    reviewCount: 89,
    sellerId: "forge-studio",
    featured: true,
    popular: true,
    tags: ["Web", "Conversion"],
    thumbGradient: "linear-gradient(135deg, #050508 0%, #ff6b00 55%, #ff2200 100%)",
  },
  {
    id: "creator-growth-pack",
    title: "Creator Growth Pack",
    tagline: "Content system + scheduling hooks",
    description: "Templates, hooks library, and posting workflow for creators.",
    includes: ["30 hooks", "Notion hub", "Schedule blueprint", "1 strategy call"],
    price: 99,
    priceLabel: "$99",
    categoryId: "content",
    deliveryHours: 24,
    deliveryLabel: "12–24h",
    rating: 5.0,
    reviewCount: 256,
    sellerId: "forge-studio",
    featured: false,
    popular: true,
    tags: ["Growth", "Content"],
    thumbGradient: "linear-gradient(135deg, #0a0505 0%, #ff2a00 40%, #ffc14d 100%)",
  },
  {
    id: "automation-workflow",
    title: "Automation Workflow",
    tagline: "Zapier/Make/n8n pipeline",
    description: "Connect your apps — leads, sheets, CRM, notifications.",
    includes: ["Audit", "3-step pipeline", "Error alerts", "Handoff doc"],
    price: 199,
    priceLabel: "$199",
    categoryId: "automation",
    deliveryHours: 72,
    deliveryLabel: "2–3 days",
    rating: 4.7,
    reviewCount: 44,
    sellerId: "dipps",
    featured: false,
    popular: false,
    tags: ["Automation"],
    thumbGradient: "linear-gradient(135deg, #030305, #ff4d00, #881100)",
  },
  {
    id: "content-system-monthly",
    title: "Content System",
    tagline: "Repurpose engine for short-form",
    description: "Turn long video into clips, captions, and post queue.",
    includes: ["Template pack", "Caption styles", "Queue SOP", "Tooling setup"],
    price: 179,
    priceLabel: "$179",
    categoryId: "content",
    deliveryHours: 48,
    deliveryLabel: "48h",
    rating: 4.85,
    reviewCount: 91,
    sellerId: "forge-studio",
    featured: false,
    popular: false,
    tags: ["Content", "Video"],
    thumbGradient: "linear-gradient(135deg, #0c0810, #ff4d00, #ff8c00)",
  },
  {
    id: "notion-template-hub",
    title: "Notion Template Hub",
    tagline: "Ops + creator dashboard",
    description: "Pre-built Notion workspace for solo founders and creators.",
    includes: ["Dashboard", "CRM lite", "Content calendar", "Duplicate link"],
    price: 29,
    priceLabel: "$29",
    categoryId: "templates",
    deliveryHours: 1,
    deliveryLabel: "Instant",
    rating: 4.9,
    reviewCount: 890,
    sellerId: "forge-studio",
    featured: false,
    popular: true,
    tags: ["Template", "Notion"],
    thumbGradient: "linear-gradient(135deg, #111, #333, #ff4d00)",
  },
  {
    id: "ai-agent-rental",
    title: "AI Agent Setup",
    tagline: "Custom agent with your knowledge base",
    description: "RAG agent wired to docs/FAQ — deploy for support or sales.",
    includes: ["KB ingest", "Agent config", "Test suite", "Deploy script"],
    price: 249,
    priceLabel: "$249",
    categoryId: "ai",
    deliveryHours: 96,
    deliveryLabel: "4 days",
    rating: 4.8,
    reviewCount: 37,
    sellerId: "dipps",
    featured: false,
    popular: false,
    tags: ["AI", "Agent"],
    thumbGradient: "linear-gradient(135deg, #050510, #4a00ff33, #ff4d00)",
  },
  {
    id: "landing-page-template",
    title: "SaaS Landing Template",
    tagline: "Next.js + Tailwind — ship today",
    description: "Premium dark landing template with forge aesthetic.",
    includes: ["Full source", "Mobile ready", "MDX blog slot", "License"],
    price: 59,
    priceLabel: "$59",
    categoryId: "templates",
    deliveryHours: 1,
    deliveryLabel: "Instant",
    rating: 4.95,
    reviewCount: 201,
    sellerId: "forge-studio",
    featured: false,
    popular: false,
    tags: ["Template", "Next.js"],
    thumbGradient: "linear-gradient(135deg, #030305, #ff2200, #ffb800)",
  },
];

export const OFFERS: OfferBundle[] = [
  {
    id: "creator-starter",
    title: "Creator Starter Pack",
    tagline: "Brand + content + Discord in one drop",
    price: 199,
    priceLabel: "$199",
    originalPrice: 327,
    deliveryLabel: "48h bundle",
    limited: true,
    badge: "DROP",
    includes: ["Brand Kit Pro", "Creator Growth Pack", "Discord Nitro Branding"],
    productIds: ["brand-kit-pro", "creator-growth-pack", "discord-nitro-branding"],
    thumbGradient: "linear-gradient(135deg, #ff2200, #ffb800, #1a0500)",
  },
  {
    id: "discord-growth-kit",
    title: "Discord Growth Kit",
    tagline: "Server + bot + branding",
    price: 249,
    priceLabel: "$249",
    originalPrice: 347,
    deliveryLabel: "72h bundle",
    limited: true,
    badge: "HOT",
    includes: ["Server Setup", "AI Discord Bot", "Nitro Branding Pack"],
    productIds: ["discord-setup-pro", "ai-discord-bot", "discord-nitro-branding"],
    thumbGradient: "linear-gradient(135deg, #5865f2, #ff4d00, #030305)",
  },
  {
    id: "ai-automation-bundle",
    title: "AI Automation Bundle",
    tagline: "Starter + agent + workflow",
    price: 399,
    priceLabel: "$399",
    originalPrice: 547,
    deliveryLabel: "5-day bundle",
    badge: "VALUE",
    includes: ["AI Automation Starter", "AI Agent Setup", "Automation Workflow"],
    productIds: ["ai-automation-starter", "ai-agent-rental", "automation-workflow"],
    thumbGradient: "linear-gradient(135deg, #0a0018, #ff4d00, #ffb800)",
  },
];
