#!/usr/bin/env node
/**
 * Weekly audit report — perf delta, content changes, priorities.
 * Usage: node scripts/weekly-report.mjs [--skip-lighthouse]
 */
import fs from "node:fs";
import path from "node:path";
import { spawnSync } from "node:child_process";
import { fileURLToPath } from "node:url";
import {
  AUDIT_ROOT,
  collectLighthouseHistory,
  readJson,
  regressionFlags,
} from "./lib/audit-utils.mjs";
import { buildManifest } from "./lib/parse-content.mjs";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const skipLh = process.argv.includes("--skip-lighthouse");
const weekDir = path.join(AUDIT_ROOT, "weekly");
const date = new Date().toISOString().slice(0, 10);

if (!skipLh) {
  console.log("→ Running full perf audit (use --skip-lighthouse to reuse cache)…");
  spawnSync("node", ["scripts/audit-perf-all.mjs"], { cwd: root, stdio: "inherit", shell: true });
}

const current = readJson(path.join(AUDIT_ROOT, "brandforge-perf-all.json"));
const previous = readJson(path.join(weekDir, "latest-perf.json"));
const manifest = buildManifest(root);
const history = collectLighthouseHistory();
const regressions = regressionFlags(history);

const home = current?.pages?.find((p) => p.path === "/");
const prevHome = previous?.pages?.find((p) => p.path === "/");
const perfDelta = home && prevHome ? home.performance - prevHome.performance : null;
const avgDelta =
  current?.avgPerformance && previous?.avgPerformance
    ? current.avgPerformance - previous.avgPerformance
    : null;

const worst = [...(current?.pages ?? [])]
  .filter((p) => p.performance !== null)
  .sort((a, b) => a.performance - b.performance)
  .slice(0, 5);

const wins = [];
const issues = [];

if (perfDelta !== null) {
  if (perfDelta >= 0) wins.push(`Home mobile perf ${perfDelta >= 0 ? "+" : ""}${perfDelta} vs last week (${home?.performance})`);
  else issues.push(`Home mobile regressed ${perfDelta} points (${home?.performance})`);
}
if (avgDelta !== null && avgDelta >= 0) wins.push(`Site-wide avg ${current.avgPerformance} (+${avgDelta})`);
if (avgDelta !== null && avgDelta < 0) issues.push(`Site-wide avg dropped to ${current.avgPerformance} (${avgDelta})`);

for (const r of regressions) issues.push(`Sprint regression: ${r.from} → ${r.to} (−${r.drop} pts)`);

const bundles = readJson(path.join(AUDIT_ROOT, "bundles/latest.json"));
if (bundles?.homeRoute?.regressed) issues.push(`Home JS bundle +${bundles.homeRoute.deltaKb}KB`);

const images = readJson(path.join(AUDIT_ROOT, "images/latest.json"));
if (images?.oversized?.length) issues.push(`${images.oversized.length} images over 200KB`);

const priorities = [
  home && home.performance < 85 ? "P0: Home mobile perf to ≥85 (currently " + home.performance + ")" : null,
  worst[0] ? `P1: Fix worst page ${worst[0].path} (${worst[0].performance})` : null,
  bundles?.homeRoute?.regressed ? "P1: Investigate home bundle growth" : null,
  "P2: Sync GA4 A/B test results to audit/ab-tests.json",
].filter(Boolean);

const md = `# BrandForge weekly report — ${date}

Generated: ${new Date().toISOString()}

## Summary

| Metric | This week | Δ |
|--------|-----------|---|
| Home mobile perf | ${home?.performance ?? "n/a"} | ${perfDelta !== null ? (perfDelta >= 0 ? "+" : "") + perfDelta : "n/a"} |
| Site-wide avg | ${current?.avgPerformance ?? "n/a"} | ${avgDelta !== null ? (avgDelta >= 0 ? "+" : "") + avgDelta : "n/a"} |
| Indexable pages | ${manifest.total} | — |
| LCP (home) | ${home?.lcp ? Math.round(home.lcp) + "ms" : "n/a"} | — |
| TBT (home) | ${home?.tbt ? Math.round(home.tbt) + "ms" : "n/a"} | — |

## Wins

${wins.length ? wins.map((w) => `- ${w}`).join("\n") : "- _(none this week)_"}

## Regressions / issues

${issues.length ? issues.map((i) => `- ${i}`).join("\n") : "- None flagged"}

## Worst pages (mobile perf)

| Page | Score | LCP |
|------|-------|-----|
${worst.map((p) => `| ${p.path} | ${p.performance} | ${p.lcp ? Math.round(p.lcp) + "ms" : "—"} |`).join("\n")}

## Priorities for next week

${priorities.map((p, i) => `${i + 1}. ${p}`).join("\n")}

## Lighthouse history (home mobile)

${history.map((h) => `- **${h.label}**: ${h.homeMobile}${h.siteWideAverage ? ` (site avg ${h.siteWideAverage})` : ""}`).join("\n")}

---
_Auto-generated by \`node scripts/weekly-report.mjs\`_
`;

fs.mkdirSync(weekDir, { recursive: true });
fs.writeFileSync(path.join(weekDir, `${date}.md`), md);
fs.writeFileSync(path.join(weekDir, "latest.md"), md);
if (current) fs.writeFileSync(path.join(weekDir, "latest-perf.json"), JSON.stringify(current, null, 2));

console.log(`✓ weekly report → audit/weekly/${date}.md`);

spawnSync("node", ["scripts/notify-discord.mjs", "weekly", md.slice(0, 1800)], {
  cwd: root,
  stdio: "inherit",
  shell: true,
});
