import type { MetadataRoute } from "next";

export default function robots(): MetadataRoute.Robots {
  return {
    rules: [
      {
        userAgent: "*",
        allow: [
          "/",
          "/marketplace",
          "/leaderboard",
          "/plans",
          "/p/",
          "/u/",
          "/feed",
          "/squads",
          "/agents",
          "/explore",
          "/about",
          "/help",
          "/product",
          "/privacy",
          "/terms",
          "/cookies",
          "/blog",
          "/press",
          "/login",
          "/services/",
          "/requests/",
          "/studio/",
        ],
        disallow: [
          // Auth-gated private areas
          "/chat",
          "/settings",
          "/welcome",
          "/auth",
          "/payment",
          "/messages",
          "/inbox",
          "/bid",
          "/notifications",
          "/_",
          "/_components",
          "/_lib",
          "/_hooks",
          "/_utils",
          "/_types",
          "/_services",
          "/_requests",
          // Action gates behind auth
          "/services/new",
          "/requests/new",
          "/services/*/edit",
          "/requests/*/edit",
          "/studio/*",
          "/agents/studio",
          "/agents/deployments/*/manage",
          "/ai/brief-generator",
          "/ai/proposal-writer",
          "/squads/new",
          "/squads/*/manage",
          // API and data endpoints
          "/api/",
          "/api/*",
          "/og/",
          "/og/*",
          "/embed/",
          "/embed/*",
          "/_next/",
          "/_next/*",
          // Query params that create duplicates
          "/*?*ref=",
          "/*?*utm_",
          "/*?*fbclid=",
          "/*?*gclid=",
          "/*?*session_id=",
          "/*?*redirect=",
          "/*?*callback=",
          "/*?*next=",
          "/*?*tab=",
          "/*?*sort=",
          // User-specific paths that shouldn't be crawled
          "/dashboard",
          "/profile",
          "/wallet",
          "/deals",
          "/history",
          "/earnings",
        ],
      },
      // Crawl-delay for aggressive bots
      {
        userAgent: "AhrefsBot",
        crawlDelay: 2,
      },
      {
        userAgent: "SemrushBot",
        crawlDelay: 2,
      },
    ],
    sitemap: "https://brandforge.gg/sitemap.xml",
    host: "https://brandforge.gg",
  };
}
