import type { PortfolioProject } from "@/types/portfolio";

const DEFAULT_SERVICES = [
  { label: "Web design & development", href: "/services/web-design/" },
  { label: "Brand identity", href: "/services/brand-identity/" },
] as const;

export const PORTFOLIO_PROJECTS: readonly PortfolioProject[] = [
  {
    slug: "whiteskyhosting",
    name: "Whiteskyhosting.com",
    category: "SaaS / Hosting",
    status: "live",
    description:
      "Hosting and VPS company — full design and development from scratch with conversion-focused pricing and plan comparison tables.",
    tags: ["SaaS", "Hosting", "B2B", "Web"],
    mockupType: "browser",
    brandGradient: ["#0ea5e9", "#0369a1"],
    url: "https://whiteskyhosting.com",
    ogImageUrl: "https://whiteskyhosting.com/og-image.png",
    timeline: "3–4 weeks",
    teamSize: "2 — design + full stack",
    outcomeMetric: "Live production site",
    brief: [
      "A hosting provider needed a credible web presence that converts operators comparing VPS plans — not a generic template with buried pricing.",
    ],
    built: [
      "Full brand-aligned marketing site from scratch",
      "Plan comparison tables and trust copy",
      "Conversion-focused pricing page structure",
      "Responsive layout and performance-first delivery",
    ],
    stack: ["Next.js", "Tailwind CSS", "Static export"],
    outcome: [
      "Live at whiteskyhosting.com with clear plan positioning",
      "Trust and pricing clarity for B2B hosting buyers",
    ],
    relatedServices: DEFAULT_SERVICES,
  },
  {
    slug: "carspotlive",
    name: "CarSpotLive",
    category: "Mobile App / iOS & Android",
    status: "live",
    description:
      "Full car-spotting mobile app — UI/UX, native iOS and Android, real-time mapping, Firebase backend, App Store December 2024.",
    tags: ["Mobile", "iOS", "Android", "Firebase", "Maps API", "Real-Time"],
    mockupType: "phone",
    brandGradient: ["#7c3aed", "#4c1d95"],
    url: "https://apps.apple.com/us/app/carspot-live/id6739596635",
    timeline: "10+ weeks",
    teamSize: "3 — design, iOS/Android, backend",
    outcomeMetric: "App Store live Dec 2024",
    brief: [
      "Founders needed a real product — not a landing page — with maps, live sharing, and community features that pass store review.",
    ],
    built: [
      "End-to-end UI/UX for spotting workflow",
      "Native iOS and Android applications",
      "Real-time location and photo sharing APIs",
      "Firebase backend and community features",
      "App Store submission and release",
    ],
    stack: ["React Native", "Firebase", "Maps API", "iOS", "Android"],
    outcome: [
      "Shipped to the App Store with live mapping and sharing",
      "Full product handoff — not a prototype",
    ],
    relatedServices: [
      { label: "Mobile apps", href: "/services/mobile-apps/" },
      { label: "Web design", href: "/services/web-design/" },
    ],
    highlights: [
      {
        stat: "App Store live",
        context: "Native iOS and Android shipped in 10 weeks — full product, not a prototype",
        serviceHref: "/services/mobile-apps/",
        serviceLabel: "Mobile apps",
      },
      {
        stat: "2x faster intake",
        context: "Branded lander + store assets replaced DMs-only funnel before launch",
        serviceHref: "/services/brand-identity/",
        serviceLabel: "Brand identity",
      },
    ],
    beforeAfter: {
      before: "Generic branding, DMs-only funnel, no store-ready assets",
      after: "Full mobile product — App Store live with maps, sharing, and brand kit",
    },
    showcaseVideo: "",
  },
  {
    slug: "directfiber",
    name: "DirectFiber",
    category: "SaaS / Enterprise",
    status: "live",
    description:
      "Enterprise ISP portal with custom billing — customer portal, plan management, usage dashboards, and billing engine.",
    tags: ["Enterprise", "SaaS", "ISP", "Billing", "B2B"],
    mockupType: "browser",
    brandGradient: ["#06b6d4", "#0e7490"],
    timeline: "8+ weeks",
    teamSize: "3 — design, backend, frontend",
    outcomeMetric: "Production portal live",
    brief: ["ISP needed a customer-facing portal with billing logic — not spreadsheets and email threads."],
    built: [
      "Customer portal and plan management UI",
      "Usage dashboards for account holders",
      "Custom billing engine integration",
      "Role-based access and admin views",
    ],
    stack: ["Node.js", "PostgreSQL", "React", "REST API"],
    outcome: ["Operators manage plans and billing in one portal"],
    relatedServices: DEFAULT_SERVICES,
  },
  {
    slug: "drain-cx",
    name: "Drain.cx",
    category: "E-commerce / Gaming",
    status: "live",
    description:
      "Scripts and competitive tools for Rust, Rainbow Six Siege, and Apex Legends — full e-commerce storefront and delivery.",
    tags: ["E-commerce", "Gaming", "Scripts", "Web"],
    mockupType: "browser",
    brandGradient: ["#ef4444", "#7f1d1d"],
    url: "https://drain.cx",
    timeline: "4 weeks",
    teamSize: "3 — design, frontend, motion",
    outcomeMetric: "Live at drain.cx",
    brief: ["Gaming tools brand needed pixel-accurate Figma-to-production with category navigation and FAQ for buyers."],
    built: [
      "Full e-commerce storefront and checkout flow",
      "Product catalog with game-specific categories",
      "Bento FAQ and scroll-enhanced sections",
      "Ultrawide and mobile responsive layouts",
    ],
    stack: ["Next.js", "Tailwind CSS", "Motion"],
    outcome: ["Production storefront serving gaming buyers with on-site FAQ"],
    relatedServices: [{ label: "Web design", href: "/services/web-design/" }],
    highlights: [
      {
        stat: "2x conversion",
        context: "Category navigation + FAQ reduced buyer bounce on cold forum traffic",
        serviceHref: "/services/web-design/",
        serviceLabel: "Web design",
      },
      {
        stat: "4-week ship",
        context: "Figma-to-production with motion sections — live at drain.cx",
        serviceHref: "/services/brand-identity/",
        serviceLabel: "Brand identity",
      },
    ],
    beforeAfter: {
      before: "Template store, buried pricing, no category navigation",
      after: "Custom storefront with game categories, FAQ, and motion — live at drain.cx",
    },
    showcaseVideo: "",
    vouch: {
      quote: "Designs are not from this world. Such a good guy with so much heart and passion.",
      who: "@Can",
      from: "Discord · Aug 2025",
    },
  },
  {
    slug: "boostingfactory",
    name: "Boostingfactory.com",
    category: "E-commerce / Gaming",
    status: "live",
    description:
      "Boosting service for HotS, LoL, MW, Apex, and Overwatch — order system, service catalog, and trust signals from scratch.",
    tags: ["E-commerce", "Gaming", "Boosting", "Web"],
    mockupType: "browser",
    brandGradient: ["#f59e0b", "#b45309"],
    url: "https://boostingfactory.com",
    timeline: "3–5 weeks",
    teamSize: "2 — design + dev",
    outcomeMetric: "Live storefront",
    brief: ["Operator needed a trustworthy catalog and checkout for multi-game boosting SKUs."],
    built: ["Service catalog by game", "Order flow and trust copy", "Responsive storefront", "Payment-ready structure"],
    stack: ["Next.js", "Tailwind", "E-commerce"],
    outcome: ["Live multi-game boosting storefront"],
    relatedServices: DEFAULT_SERVICES,
  },
  {
    slug: "fluorite-store",
    name: "Fluorite.store",
    category: "E-commerce / Gaming",
    status: "live",
    description:
      "Competitive edge tools for MLBB, Free Fire, and COD Mobile — full design and development from scratch.",
    tags: ["E-commerce", "Mobile Gaming", "Tools", "Web"],
    mockupType: "browser",
    brandGradient: ["#a855f7", "#6b21a8"],
    url: "https://fluorite.store",
    timeline: "3–4 weeks",
    teamSize: "2",
    outcomeMetric: "Live store",
    brief: ["Mobile gaming tools seller needed dark UI, fast catalog, and delivery clarity."],
    built: ["Product pages per title", "Checkout and delivery UX", "Brand-dark visual system"],
    stack: ["Next.js", "Tailwind"],
    outcome: ["Live tools storefront for mobile competitive games"],
    relatedServices: DEFAULT_SERVICES,
  },
  {
    slug: "passle",
    name: "Passle",
    category: "SaaS / Creator Platform",
    status: "live",
    description:
      "Creator monetization — subscriptions, PPV, tipping, Keys wallet. 95% revenue split. Crypto, Apple Pay, cards.",
    tags: ["SaaS", "Creator Economy", "Payments", "Crypto", "Platform"],
    mockupType: "browser",
    brandGradient: ["#ec4899", "#9d174d"],
    url: "https://passle.vercel.app",
    timeline: "8+ weeks",
    teamSize: "3 — product, design, full stack",
    outcomeMetric: "Platform live",
    brief: ["Creators needed monetization rails with high revenue share and multiple payment rails."],
    built: [
      "Subscription and pay-per-view flows",
      "One-tap tipping and Keys wallet",
      "Creator dashboard and payout logic",
      "Crypto, Apple Pay, and card integrations",
    ],
    stack: ["Next.js", "Payments API", "Crypto", "Vercel"],
    outcome: ["Live creator platform with 95% revenue split positioning"],
    relatedServices: [
      { label: "Web design", href: "/services/web-design/" },
      { label: "Automation", href: "/services/automation/" },
    ],
  },
  {
    slug: "dyotravel",
    name: "Dyo Travel",
    category: "Travel / Full Stack",
    status: "live",
    description:
      "Hotel booking with API-driven dynamic pricing, room listings, cancellation policies, deployment and live support.",
    tags: ["Travel", "Full Stack", "API", "Booking"],
    mockupType: "browser",
    brandGradient: ["#14b8a6", "#0f766e"],
    url: "https://dyotravel.com",
    timeline: "6 weeks",
    teamSize: "3",
    outcomeMetric: "Live booking platform",
    brief: ["Travel operator needed real pricing APIs — not static mock booking forms."],
    built: [
      "Hotel search and room listings",
      "Dynamic pricing integration",
      "Cancellation policy surfaces",
      "Production deployment and support handoff",
    ],
    stack: ["Node.js", "API", "React", "PostgreSQL"],
    outcome: ["Live booking at dyotravel.com with API-driven rates"],
    relatedServices: DEFAULT_SERVICES,
  },
  {
    slug: "repsheets",
    name: "Repsheets",
    category: "Web",
    status: "live",
    description: "Live web property — design and development delivery for operator use case.",
    tags: ["Web", "Live"],
    mockupType: "browser",
    brandGradient: ["#64748b", "#334155"],
    url: "https://repsheets.net",
    timeline: "2–3 weeks",
    teamSize: "2",
    outcomeMetric: "Live at repsheets.net",
    brief: ["Operator needed a clean, fast web presence for their sheet workflow brand."],
    built: ["Marketing site", "Responsive layout", "Performance-focused delivery"],
    stack: ["Next.js", "Tailwind"],
    outcome: ["Live site at repsheets.net"],
    relatedServices: DEFAULT_SERVICES,
  },
  {
    slug: "cascade-markets",
    name: "Cascade Markets",
    category: "Web3 / Landing Page",
    status: "archived",
    description:
      "Web3 crypto prediction market landing — performance-first structure. Client discontinued post-delivery.",
    tags: ["Web3", "Landing Page", "Next.js", "Tailwind", "Performance"],
    mockupType: "browser",
    brandGradient: ["#7c3aed", "#312e81"],
    url: "https://cascade.markets",
    timeline: "2–3 weeks",
    teamSize: "2",
    outcomeMetric: "Delivered production-ready",
    brief: ["Needed a credible Web3 landing before paid traffic — delivered, later discontinued by client."],
    built: ["Hero and CTA hierarchy", "Web3 visual language", "Performance-first static delivery"],
    stack: ["Next.js", "Tailwind", "Static export"],
    outcome: ["Production-ready landing delivered — client later discontinued product"],
    relatedServices: DEFAULT_SERVICES,
    highlights: [
      {
        stat: "2–3 week ship",
        context: "Web3 landing with performance-first static export before paid traffic",
        serviceHref: "/services/web-design/",
        serviceLabel: "Web design",
      },
    ],
    beforeAfter: {
      before: "Generic Web3 template, unclear CTA hierarchy, slow first paint",
      after: "Performance-first landing with credible Web3 visual language before paid traffic",
    },
  },
  {
    slug: "grindnode",
    name: "Grindnode",
    category: "SaaS / Hosting",
    status: "archived",
    description: "Hosting and VPS provider — full design and development. Client discontinued operations.",
    tags: ["SaaS", "Hosting", "Web"],
    mockupType: "browser",
    brandGradient: ["#475569", "#1e293b"],
    timeline: "3 weeks",
    teamSize: "2",
    outcomeMetric: "Delivered — ops discontinued",
    brief: ["Hosting brand needed full site — delivered before client shut down."],
    built: ["Plan pages", "Trust copy", "Full site design and build"],
    stack: ["Next.js", "Tailwind"],
    outcome: ["Complete delivery — client discontinued operations"],
    relatedServices: DEFAULT_SERVICES,
  },
  {
    slug: "cloutscout",
    name: "Cloutscout.ai",
    category: "AI / SaaS",
    status: "archived",
    description: "AI-powered Instagram and TikTok creator discovery. Client went silent post-delivery.",
    tags: ["AI", "SaaS", "Social Media", "Discovery"],
    mockupType: "browser",
    brandGradient: ["#8b5cf6", "#5b21b6"],
    timeline: "6 weeks",
    teamSize: "3",
    outcomeMetric: "Product delivered",
    brief: ["Creator discovery SaaS with AI ranking and search — delivered, client inactive after handoff."],
    built: ["Discovery UI", "Creator ranking views", "Dashboard and filters"],
    stack: ["Next.js", "AI API", "PostgreSQL"],
    outcome: ["Full product delivery — client went silent post-handoff"],
    relatedServices: [{ label: "AI tools", href: "/services/ai-tools/" }],
  },
  {
    slug: "lava-pw",
    name: "Lava.pw",
    category: "Blockchain / AI",
    status: "archived",
    description: "AI Agent for SUI Blockchain — full product design and development from scratch.",
    tags: ["SUI", "Blockchain", "AI", "Web3"],
    mockupType: "browser",
    brandGradient: ["#06b6d4", "#164e63"],
    url: "https://lava.pw",
    timeline: "5 weeks",
    teamSize: "3",
    outcomeMetric: "Shipped product",
    brief: ["Web3 team needed an AI agent product surface for SUI — built end-to-end."],
    built: ["Product UI", "Agent interaction flows", "On-chain positioning pages"],
    stack: ["Next.js", "SUI", "AI"],
    outcome: ["Delivered AI agent product at lava.pw"],
    relatedServices: [{ label: "AI tools", href: "/services/ai-tools/" }],
  },
  {
    slug: "sui-blockchain-app",
    name: "SUI Blockchain App Fork",
    category: "Blockchain / Full Stack",
    status: "archived",
    description:
      "Forked Solana aggregation app for SUI — team of 4, vector DB, real-time pipelines, 2 weeks, $9k budget.",
    tags: ["SUI", "Solana", "Blockchain", "Backend", "Real-Time"],
    mockupType: "phone",
    brandGradient: ["#22d3ee", "#155e75"],
    budgetPublic: "$9,000 scoped",
    timeline: "2 weeks",
    teamSize: "4",
    outcomeMetric: "Delivered on budget",
    brief: ["Client needed a rapid SUI fork of an existing Solana data product with backend rebuild."],
    built: [
      "Vector database and real-time pipelines",
      "Custom tokenization layer",
      "Frontend adaptation for SUI wallets",
      "Backend rebuild with 4-person squad",
    ],
    stack: ["Rust", "Vector DB", "SUI", "React Native"],
    outcome: ["Delivered in two weeks within $9,000 budget"],
    relatedServices: [{ label: "Mobile apps", href: "/services/mobile-apps/" }],
    highlights: [
      {
        stat: "2-week rebuild",
        context: "Full SUI fork with vector DB and wallet flows — $9k fixed scope",
        serviceHref: "/services/mobile-apps/",
        serviceLabel: "Mobile apps",
      },
    ],
  },
  {
    slug: "jarro-ai",
    name: "Jarro AI",
    category: "AI / Trading",
    status: "archived",
    description:
      "Visual AI for trading chart analysis — candlesticks, S/R, risk flags. Drag-drop PNG/JPG, sub-2.5s analysis. 5 weeks.",
    tags: ["AI", "Trading", "Fintech", "Computer Vision"],
    mockupType: "browser",
    brandGradient: ["#10b981", "#065f46"],
    timeline: "5 weeks",
    teamSize: "2 — AI + frontend",
    outcomeMetric: "Sub-2.5s analysis",
    brief: ["Trader client Crum needed chart screenshot analysis without wallet connect — freemium + Pro tier."],
    built: [
      "Drag-and-drop chart upload",
      "Vision model pipeline for pattern read",
      "Support/resistance and risk surfacing",
      "Freemium and Pro tier gating",
    ],
    stack: ["Python", "Vision API", "Next.js"],
    outcome: ["Analysis under 2.5 seconds per chart upload"],
    relatedServices: [{ label: "AI tools", href: "/services/ai-tools/" }],
  },
  {
    slug: "linkedin-automation",
    name: "LinkedIn Automation Platform",
    category: "Automation / SaaS",
    status: "archived",
    description:
      "$4,660 scoped build — account creator, USPhonebook scraper, OctaBrowser, Clerk Auth, milestone payments.",
    tags: ["Automation", "SaaS", "LinkedIn", "Scraper", "Electron"],
    mockupType: "browser",
    brandGradient: ["#0a66c2", "#004182"],
    budgetPublic: "$4,660",
    timeline: "6 weeks (modular)",
    teamSize: "2 — automation + backend",
    outcomeMetric: "Milestone delivery",
    brief: ["Operator needed modular automation tooling with compliance-aware account management."],
    built: [
      "LinkedIn account creation workflows",
      "USPhonebook scraper integration",
      "OctaBrowser multi-account management",
      "Clerk Auth and modular milestone billing",
    ],
    stack: ["Electron", "Node.js", "Clerk", "Automation"],
    outcome: ["Delivered scoped modules with milestone payments"],
    relatedServices: [{ label: "Automation", href: "/services/automation/" }],
  },
  {
    slug: "gazedvalleybeef",
    name: "GazedValleyBeef",
    category: "Content Creation",
    status: "archived",
    description:
      "Three months Instagram content for premium WA grass-fed Black Angus — farm-to-table visual storytelling.",
    tags: ["Content", "Instagram", "Social Media", "Agriculture"],
    mockupType: "tablet",
    brandGradient: ["#78716c", "#44403c"],
    timeline: "3 months retainer",
    teamSize: "1–2 — content + design",
    outcomeMetric: "3 months delivered",
    brief: ["Premium beef farm needed business-grade social from raw farm photography."],
    built: [
      "Instagram content calendar",
      "Farm-to-table visual edits",
      "Caption and story templates",
    ],
    stack: ["Instagram", "Content design", "Photography edit"],
    outcome: ["Three months of consistent farm-to-table social content"],
    relatedServices: [{ label: "Social media", href: "/services/social-media/" }],
  },
  {
    slug: "valaccs",
    name: "ValAccs.com",
    category: "E-commerce / Gaming",
    status: "archived",
    description:
      "Valorant account store — multi-category sorting, Billgang payments, dark Valorant-inspired UI, ~2 week delivery.",
    tags: ["E-commerce", "Svelte", "Gaming", "Payments"],
    mockupType: "browser",
    brandGradient: ["#ff4655", "#1f2937"],
    timeline: "~2 weeks",
    teamSize: "2",
    outcomeMetric: "Store delivered",
    brief: ["Digital goods store needed fast catalog, filters, and Billgang checkout."],
    built: [
      "Multi-category product sorting",
      "Billgang payment gateway",
      "Dark Valorant-inspired UI system",
    ],
    stack: ["Svelte", "Billgang", "E-commerce"],
    outcome: ["Delivered storefront in approximately two weeks"],
    relatedServices: DEFAULT_SERVICES,
    highlights: [
      {
        stat: "~2 week ship",
        context: "Valorant account store with Billgang checkout and category filters",
        serviceHref: "/services/web-design/",
        serviceLabel: "Web design",
      },
    ],
  },
  {
    slug: "ai-voice-receptionist",
    name: "AI Voice Receptionist",
    category: "AI / Voice / SaaS",
    status: "upcoming",
    description:
      "Prototype AI receptionist for dental clinics in France — appointments and patient queries via voice, in active development.",
    tags: ["AI", "Voice", "Healthcare", "French Market", "SaaS"],
    mockupType: "phone",
    brandGradient: ["#3b82f6", "#1e40af"],
    timeline: "In development",
    teamSize: "2 — voice + backend",
    outcomeMetric: "Prototype in progress",
    brief: ["Healthcare operator needs voice-first reception automation — no human operator required for routine calls."],
    built: [
      "Voice booking flows (in progress)",
      "Patient query handling (in progress)",
      "Clinic workflow integration (in progress)",
    ],
    stack: ["Voice AI", "Telephony API", "Node.js"],
    outcome: ["Active prototype development — client details confidential"],
    relatedServices: [{ label: "AI tools", href: "/services/ai-tools/" }],
    confidentialNote: "Client name and pricing not disclosed.",
  },
  {
    slug: "crystal-wars",
    name: "Crystal Wars",
    category: "Game Development / Unity",
    status: "upcoming",
    description:
      "Unity strategy game — civilization selection, troop deployment, ranked play. Full dev negotiations in progress.",
    tags: ["Unity", "Game Dev", "Strategy", "Mobile/PC"],
    mockupType: "tablet",
    brandGradient: ["#6366f1", "#4338ca"],
    url: "https://crystal-war.com",
    timeline: "Negotiation",
    teamSize: "TBD — game squad",
    outcomeMetric: "Pre-production",
    brief: [
      "Strategy game needs full build from design through engine and multiplayer — BrandForge in active negotiations for the engagement.",
    ],
    built: [
      "Game design and UI scope (planned)",
      "Unity engine implementation (planned)",
      "Multiplayer and ranked systems (planned)",
    ],
    stack: ["Unity", "C#", "Multiplayer"],
    outcome: ["Active development negotiations — see crystal-war.com"],
    relatedServices: [{ label: "Mobile apps", href: "/services/mobile-apps/" }],
    confidentialNote: "Budget, client identity, and scope numbers are confidential.",
  },
  {
    slug: "confidential-engagement",
    name: "Confidential Engagement",
    category: "Under NDA",
    status: "upcoming",
    description: "Confidential project under NDA. Contact us to discuss your own.",
    tags: ["NDA", "Confidential"],
    mockupType: "browser",
    brandGradient: ["#374151", "#111827"],
    timeline: "NDA",
    teamSize: "Scoped per client",
    outcomeMetric: "Private",
    brief: ["Selective engagements under NDA — contact Discord or Telegram to discuss fit."],
    built: ["Scope defined per engagement under NDA"],
    stack: ["Varies"],
    outcome: ["Contact BrandForge for confidential work"],
    relatedServices: DEFAULT_SERVICES,
  },
] as const;

export const PORTFOLIO_SLUGS = PORTFOLIO_PROJECTS.map((p) => p.slug);

export type PortfolioSlug = (typeof PORTFOLIO_SLUGS)[number];

export function getProjectBySlug(slug: string): PortfolioProject | undefined {
  return PORTFOLIO_PROJECTS.find((p) => p.slug === slug);
}

export function projectsByStatus(status: PortfolioProject["status"]): readonly PortfolioProject[] {
  return PORTFOLIO_PROJECTS.filter((p) => p.status === status);
}
